FROM node:latest
RUN apt-get update && apt-get install -y nginx

WORKDIR /code
ADD . /code

RUN yarn install
RUN yarn global add webpack
RUN yarn global add webpack-cli
RUN webpack

ENV NODE_ENV production
EXPOSE 8080
