stages:
  - build
  - setup
  - test
  - cleanup

build:
  tags:
    - docker-shell
  stage: build
  script:
    - cd envs/dev
    - docker-compose build

setup:
  tags:
    - docker-shell
  stage: setup
  script:
    - cd envs/dev
    - docker volume create vol_smart_pgdata && docker volume create vol_smart_data
    - docker-compose up -d
  after_script:
    - cd envs/dev
    - docker-compose stop

test_frontend:
  tags:
    - docker-shell
  script:
    - cd envs/dev
    - docker-compose start
    - docker exec -i smart_frontend bash -c "./run_tests.sh"
  after_script:
    - cd envs/dev
    - docker-compose stop

test_backend:
  tags:
    - docker-shell
  script:
    - cd envs/dev
    - docker-compose start
    - docker exec -i backend bash -c "./run_tests.sh"
  after_script:
    - cd envs/dev
    - docker-compose stop

cleanup:
  tags:
    - docker-shell
  stage: cleanup
  allow_failure: true
  script:
    - cd envs/dev
    - docker-compose down
    - docker volume remove vol_smart_pgdata
    - docker volume remove vol_smart_data
  when: always
