FROM python:3.6.0
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=smart.settings
ENV DJANGO_CONFIGURATION=Prod
RUN apt-get update && apt-get install -y netcat-traditional
WORKDIR /code
ADD ./requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
RUN pip install gunicorn gevent
ADD ./django/ /code/
RUN mkdir -p /data/data_files /data/tf_idf /data/model_pickles /data/code_books data/static_files
