# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20170615_1935"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Project"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="datalabel",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Label"
            ),
        ),
    ]
