# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20170619_1458"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Data"
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Queue"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.User"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="assigneddata",
            unique_together=set([("user", "data", "queue")]),
        ),
    ]
