# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20170619_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
