# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 16:43
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigneddata",
            name="assigned_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
