# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20170621_1904"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
