# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 20:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20170621_1904"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.User",
            ),
        ),
    ]
