# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_Make_Queue_user_correctly_nullable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="labels",
            new_name="labeled_data",
        ),
    ]
