# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="hash",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
