# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_data_hash"),
        ("core", "0010_Make_AssignedData_unique_on_user_and_data"),
    ]

    operations = []
