# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 19:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_projectpermissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="projectpermissions",
            unique_together=set([("user", "project")]),
        ),
    ]
