# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20170919_1915"),
        ("core", "0011_merge_20170919_1319"),
    ]

    operations = []
