# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_merge_20170920_1659"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="core.Project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.User"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projectpermissions",
            name="permission",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("CODER", "Coder")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="projectpermissions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.User"
            ),
        ),
    ]
