# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20170928_1801"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assigneddata",
            unique_together=set([("user", "queue", "data")]),
        ),
    ]
