# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 15:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0016_auto_20170928_1820"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "labeled_data",
                    models.ManyToManyField(
                        related_name="labelers",
                        through="core.DataLabel",
                        to="core.Data",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="assigneddata",
            name="profile",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datalabel",
            name="profile",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectpermissions",
            name="profile",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queue",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assigneddata",
            unique_together=set([("profile", "queue", "data")]),
        ),
        migrations.AlterUniqueTogether(
            name="datalabel",
            unique_together=set([("data", "profile")]),
        ),
        migrations.AlterUniqueTogether(
            name="projectpermissions",
            unique_together=set([("profile", "project")]),
        ),
        migrations.AlterField(
            model_name="project",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Profile"
            ),
        ),
        migrations.RemoveField(
            model_name="assigneddata",
            name="user",
        ),
        migrations.RemoveField(
            model_name="datalabel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="projectpermissions",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="auth_user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="labeled_data",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="user",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
