# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 19:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20171006_1504"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataprediction",
            name="predicted_class",
        ),
        migrations.AddField(
            model_name="datalabel",
            name="training_set",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataprediction",
            name="label",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.Label"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="current_training_set",
            field=models.IntegerField(default=0),
        ),
    ]
