# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20171013_1917"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dataprediction",
            unique_together=set([("data", "model", "label")]),
        ),
    ]
