# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 20:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20171019_1751"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUncertainty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("least_confident", models.FloatField()),
                ("margin_sampling", models.FloatField()),
                ("entropy", models.FloatField()),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Data"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Model"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="datauncertainty",
            unique_together=set([("data", "model")]),
        ),
    ]
