# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 15:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20171019_2029"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="current_training_set",
        ),
        migrations.AlterField(
            model_name="datalabel",
            name="training_set",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.TrainingSet",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingset",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Project"
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="training_set",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.TrainingSet",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="datalabel",
            unique_together=set([("data", "profile", "training_set")]),
        ),
    ]
