# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20171026_1513"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="df_idx",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
