# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_data_df_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingset",
            name="celery_task_id",
            field=models.TextField(blank=True),
        ),
    ]
