# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20171030_1449"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="label",
            unique_together=set([("name", "project")]),
        ),
    ]
