# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20171102_1738"),
        ("core", "0025_datalabel_label_time"),
    ]

    operations = []
