# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_datalabel_label_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="cv_accuracy",
            field=models.FloatField(default=0.05),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="model",
            name="cv_std",
            field=models.FloatField(default=0.05),
            preserve_default=False,
        ),
    ]
