# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_merge_20171107_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalabel",
            name="time_to_label",
            field=models.IntegerField(null=True),
        ),
    ]
