# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_auto_20171107_1546"),
        ("core", "0026_auto_20171107_1927"),
    ]

    operations = []
