# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_auto_20171108_1631"),
        ("core", "0028_merge_20171108_2016"),
    ]

    operations = []
