# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_merge_20171108_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
