# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-28 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20180627_1603"),
        ("core", "0030_queue_admin"),
    ]

    operations = []
