# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_merge_20180628_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
