# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 18:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_merge_20180628_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="num_users_irr",
            field=models.IntegerField(
                default=2, validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="percentage_irr",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
