# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_auto_20180717_1825"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="irr_ind",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queue",
            name="irr",
            field=models.BooleanField(default=False),
        ),
    ]
