# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 19:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_datalabel_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelChangeLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_label", models.TextField()),
                ("new_label", models.TextField()),
                ("change_timestamp", models.DateTimeField(default=None, null=True)),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Data"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Profile"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="labelchangelog",
            unique_together=set([("data", "profile")]),
        ),
    ]
