# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_project_codebook_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="batch_size",
            field=models.IntegerField(default=30),
        ),
    ]
