# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_labelchangelog_project"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="labelchangelog",
            unique_together=set([]),
        ),
    ]
