# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_auto_20180717_1849"),
        ("core", "0038_auto_20180717_1442"),
    ]

    operations = []
