# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_auto_20180717_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="upload_id",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
