# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-18 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_auto_20180718_1335"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrlog",
            name="timestamp",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
