# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20180725_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="df_idx_hash",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="data",
            unique_together=set([("hash", "df_idx_hash")]),
        ),
    ]
