# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_auto_20180717_1442"),
        ("core", "0041_auto_20180713_1822"),
    ]

    operations = []
