# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_merge_20180717_2020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
