# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_merge_20180717_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRRLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Data')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Label')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='irrlog',
            unique_together=set([('data', 'profile')]),
        ),
    ]
