# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_auto_20180730_1837"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="df_idx_hash",
            new_name="upload_id_hash",
        ),
        migrations.AlterUniqueTogether(
            name="data",
            unique_together=set([("hash", "upload_id_hash")]),
        ),
    ]
