# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_auto_20180724_1717"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="irr",
        ),
        migrations.AddField(
            model_name="queue",
            name="type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("irr", "IRR"), ("normal", "Normal")],
                default="normal",
                max_length=6,
            ),
        ),
    ]
