# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_data_df_idx"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="data",
            unique_together=set([("hash", "upload_id_hash", "project")]),
        ),
    ]
