# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_auto_20180724_1732"),
        ("core", "0044_auto_20180724_1508"),
    ]

    operations = []
