# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_merge_20180725_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="classifier",
            field=models.CharField(
                choices=[
                    ("logistic regression", "Logistic Regression (default)"),
                    (
                        "svm",
                        "Support Vector Machine (warning: slower for large datasets)",
                    ),
                    ("random forest", "Random Forest"),
                    ("gnb", "Gaussian Naive Bayes"),
                ],
                default="logistic regression",
                max_length=19,
            ),
        ),
    ]
