# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_auto_20180724_1508"),
        ("core", "0045_auto_20180730_1929"),
    ]

    operations = []
