# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_merge_20180731_1734'),
        ('core', '0045_merge_20180727_1228'),
    ]

    operations = [
    ]
