# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_auto_20180802_1248"),
        ("core", "0047_merge_20180801_1859"),
    ]

    operations = []
