# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-13 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_adminprogress'),
        ('core', '0048_merge_20180807_1939'),
    ]

    operations = [
    ]
