# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-10 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_adminprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalabel",
            name="label_reason",
            field=models.TextField(default=""),
        ),
    ]
