# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-12 18:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_adminprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(null=True)),
                ("username", models.TextField(blank=True, null=True)),
                ("url", models.URLField(null=True)),
                ("user_string1", models.TextField(blank=True, null=True)),
                ("user_string2", models.TextField(blank=True, null=True)),
                ("post_string1", models.TextField(blank=True, null=True)),
                ("post_string2", models.TextField(blank=True, null=True)),
                ("post_date1", models.DateTimeField(null=True)),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Data",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_source", models.TextField(blank=True, null=True)),
                ("has_created_date", models.BooleanField(default=False)),
                ("has_username", models.BooleanField(default=False)),
                ("has_url", models.BooleanField(default=False)),
                ("user_string1_name", models.TextField(null=True)),
                ("user_string2_name", models.TextField(null=True)),
                ("post_string1_name", models.TextField(null=True)),
                ("post_string2_name", models.TextField(null=True)),
                ("post_date1_name", models.TextField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Project"
                    ),
                ),
            ],
        ),
    ]
