# Generated by Django 3.2.3 on 2021-08-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_model_cv_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaDataField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.data"
                    ),
                ),
                (
                    "metadata_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.metadatafield",
                    ),
                ),
            ],
            options={
                "unique_together": {("data", "metadata_field")},
            },
        ),
    ]
