# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20180813_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauncertainty',
            name='qbc',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
