# Generated by Django 3.2.3 on 2021-08-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_metadata_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="value",
            field=models.TextField(null=True),
        ),
    ]
