# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_auto_20191212_2152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
