# Generated by Django 3.2.3 on 2021-08-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_metadata_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
