# Generated by Django 3.2.3 on 2021-08-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_alter_metadata_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLabelSimilarityPairs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.IntegerField()),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarityPair",
                        to="core.data",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarityPair",
                        to="core.label",
                    ),
                ),
            ],
            options={
                "unique_together": {("data", "label")},
            },
        ),
    ]
