# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-31 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_auto_20191210_1527"),
        ("core", "0056_auto_20191213_1620"),
    ]

    operations = []
