# Generated by Django 3.2.3 on 2021-08-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_metadata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatafield',
            name='use_with_dedup',
            field=models.BooleanField(default=True),
        ),
    ]
