# Generated by Django 3.2.3 on 2021-09-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_metadata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_umbrella',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='umbrella_project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
