# Generated by Django 3.2.3 on 2021-09-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_project_dedup_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatafield",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadatafields",
                to="core.project",
            ),
        ),
    ]
