# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-07 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_auto_20200106_0000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="url",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
