# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_auto_20200107_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="user_url",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
