# Generated by Django 3.2.3 on 2021-09-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_datalabelsimilaritypairs"),
        ("core", "0060_alter_metadatafield_project"),
    ]

    operations = []
