# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_auto_20200108_1500"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalabel",
            name="was_skipped",
            field=models.BooleanField(default=False),
        ),
    ]
