# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_auto_20200108_1500"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="explicit_ind",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="use_explicit_ind",
            field=models.BooleanField(default=False),
        ),
    ]
