# Generated by Django 3.2.3 on 2021-09-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_merge_20210915_1627"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datalabelsimilaritypairs",
            options={"ordering": ["-similarity_score"]},
        ),
        migrations.AddField(
            model_name="project",
            name="umbrella_string",
            field=models.TextField(blank=True),
        ),
    ]
