# Generated by Django 3.2.9 on 2021-12-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_auto_20210927_1521"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalDatabase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("env_file", models.TextField()),
                ("has_ingest", models.BooleanField(default=False)),
                ("ingest_schema", models.CharField(max_length=128, null=True)),
                ("ingest_table_name", models.CharField(max_length=128, null=True)),
                ("has_export", models.BooleanField(default=False)),
                ("export_schema", models.CharField(max_length=128, null=True)),
                ("export_table_name", models.CharField(max_length=128, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="externaldatabase",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
