# Generated by Django 3.2.3 on 2021-11-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_auto_20210927_1521"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataLabelSimilarityPairs",
        ),
    ]
