# Generated by Django 3.2.9 on 2021-12-16 16:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_auto_20210927_1521"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelEmbeddings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labelEmbedding",
                        to="core.label",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DataLabelSimilarityPairs",
        ),
    ]
