# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-21 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_datalabel_was_skipped"),
        ("core", "0062_auto_20200119_1836"),
    ]

    operations = []
