# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_merge_20200121_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclebin",
            name="exclude_reason",
            field=models.TextField(default="", null=True),
        ),
    ]
