# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_recyclebin_exclude_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrlog",
            name="time_to_label",
            field=models.IntegerField(null=True),
        ),
    ]
