# Generated by Django 3.2.9 on 2022-01-30 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_alter_externaldatabase_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldatabase",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="externaldatabase",
                to="core.project",
            ),
        ),
    ]
