# Generated by Django 3.2.9 on 2022-02-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_label_embeddings_20220208_1621"),
        ("core", "0066_alter_externaldatabase_project"),
    ]

    operations = []
