# Generated by Django 3.2.9 on 2022-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_merge_20220216_1953"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="labelembeddings",
            options={"ordering": ("label_id",)},
        ),
        migrations.AlterField(
            model_name="externaldatabase",
            name="export_schema",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="externaldatabase",
            name="export_table_name",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
