# Generated by Django 3.2.9 on 2022-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_merge_20220216_1953"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="labelembeddings",
            options={"ordering": ("label_id",)},
        ),
        migrations.AlterField(
            model_name="project",
            name="ordering_method",
            field=models.CharField(
                choices=[
                    ("least confident", "By Uncertainty using Least Confident"),
                    ("margin sampling", "By Uncertainty using the Margin"),
                    ("entropy", "By Uncertainty using Entropy"),
                    ("random", "Randomly (No Active Learning)"),
                    (
                        "newest",
                        "By date added to SMART - newest first (No Active Learning)",
                    ),
                    (
                        "oldest",
                        "By date added to SMART - oldest first (No Active Learning)",
                    ),
                ],
                default="least confident",
                max_length=15,
            ),
        ),
    ]
