# Generated by Django 3.2.9 on 2022-06-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_merge_20220216_1953"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="labelembeddings",
            options={"ordering": ("label_id",)},
        ),
    ]
