# Generated by Django 3.2.9 on 2022-06-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_adjudicate_descriptions_20220510_2033"),
        ("core", "0068_auto_20220623_1327"),
    ]

    operations = []
