# Generated by Django 3.2.9 on 2022-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_adjudicate_descriptions_20220510_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatabase",
            name="cron_ingest",
            field=models.BooleanField(default=False),
        ),
    ]
