# Generated by Django 3.2.9 on 2022-04-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_alter_project_ordering_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="upload_date",
            field=models.DateField(null=True),
        ),
    ]
