# Generated by Django 3.2.9 on 2022-07-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_externaldatabase_daily_ingest"),
        ("core", "0069_merge_20220628_1849"),
    ]

    operations = []
