# Generated by Django 3.2.9 on 2022-10-03 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_adminprogress_last_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalabel",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
