# Generated by Django 3.2.9 on 2022-10-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_adminprogress_last_action'),
        ('core', '0070_merge_20220727_1406'),
    ]

    operations = [
    ]
