# Generated by Django 3.2.9 on 2022-04-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_data_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="upload_date",
            field=models.DateTimeField(null=True),
        ),
    ]
