# Generated by Django 3.2.9 on 2022-11-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_merge_20221016_1513"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatabase",
            name="cron_export",
            field=models.BooleanField(default=False),
        ),
    ]
