# Generated by Django 3.2.9 on 2022-12-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_datalabel_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatabase",
            name="export_verified_only",
            field=models.BooleanField(default=False),
        ),
    ]
