# Generated by Django 3.2.9 on 2023-07-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_auto_20230305_1909"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="data",
            index=models.Index(fields=["project"], name="core_data_project_445167_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["id"], name="core_projec_id_d85ea2_idx"),
        ),
    ]
