# Generated by Django 4.2.9 on 2024-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_auto_20230710_1905"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_coders_view_labels",
            field=models.BooleanField(default=False),
        ),
    ]
