# Generated by Django 3.2.9 on 2023-10-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_auto_20230710_1905"),
        ("core", "0076_mlmodel"),
    ]

    operations = []
