# Generated by Django 4.2.11 on 2024-07-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_project_allow_coders_view_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelMetaDataField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labelmetadatafields",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabelMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labelmetadata",
                        to="core.label",
                    ),
                ),
                (
                    "label_metadata_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.labelmetadatafield",
                    ),
                ),
            ],
            options={
                "unique_together": {("label", "label_metadata_field")},
            },
        ),
    ]
