# Generated by Django 4.2.11 on 2024-07-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_labelmetadatafield_category_labelmetadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="field_name",
        ),
        migrations.AddField(
            model_name="category",
            name="data_metadata_field",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadatacategory",
                to="core.metadatafield",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="label_metadata_field",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labelmetadatacategory",
                to="core.labelmetadatafield",
            ),
            preserve_default=False,
        ),
    ]
