# Generated by Django 4.2.11 on 2024-09-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_rename_name_category_field_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrlog",
            name="time_to_label",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
