version: '2.1'

services:
  postgres:
    extends:
      file: ../docker-common.yml
      service: postgres

  redis:
    extends:
      file: ../docker-common.yml
      service: redis

  backend:
    extends:
      file: ../docker-common.yml
      service: backend
    build:
      context: ../../backend/
      dockerfile: docker/Dockerfile.prod
    image: rti/smart-backend-prod:R_0_0_1
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - postgres
      - redis

  smart_frontend:
    extends:
      file: ../docker-common.yml
      service: smart_frontend
    build: ../../frontend/
    image: rti/smart-frontend:R_0_0_1
    command: node_modules/.bin/webpack --watch


volumes:
  smart_pgdata:
    external: true
    name: vol_smart_pgdata
  smart_data:
    external: true
    name: vol_smart_data
