services:
  postgres:
    extends:
      file: ../docker-common.yml
      service: postgres
    restart: always

  redis:
    restart: always
    extends:
      file: ../docker-common.yml
      service: redis

  backend:
    extends:
      file: ../docker-common.yml
      service: backend
    build:
      context: ../../backend/
      dockerfile: docker/Dockerfile.prod
    image: rti/smart-backend-prod:R_0_0_1
    restart: always
    ports:
      - "${EXTERNAL_BACKEND_PORT:-80}:8000"
    depends_on:
      - postgres
      - redis

  smart_frontend:
    extends:
      file: ../docker-common.yml
      service: smart_frontend
    build: ../../frontend/
    restart: always
    image: rti/smart-frontend:R_0_0_1
    command: node_modules/.bin/webpack --watch


volumes:
  smart_pgdata_15_2:
    external: true
    name: vol_smart_pgdata_15_2
  smart_data:
    external: true
    name: vol_smart_data
