version: '2.1'

services:
  postgres:
    extends:
      file: ../docker-common.yml
      service: postgres

  redis:
    extends:
      file: ../docker-common.yml
      service: redis

  smart_backend:
    extends:
      file: ../docker-common.yml
      service: smart_backend
    build:
      context: ../../backend/
      dockerfile: docker/Dockerfile.prod
    image: rti/smart-backend-prod:R_0_0_1
    restart: always
    depends_on:
      - postgres
      - redis

  smart_frontend:
    extends:
      file: ../docker-common.yml
      service: smart_frontend
    build:
      context: ../../frontend/
      dockerfile: Dockerfile.prod
    image: rti/smart-frontend-prod:R_0_0_1
    ports:
      - "${EXTERNAL_FRONTEND_PORT:-8080}:8080"
    command: nginx -c /code/nginx.conf -g "daemon off;"

volumes:
  smart_pgdata:
    external: true
    name: vol_smart_pgdata
  smart_data:
    external: true
    name: vol_smart_data
