version: '2.1'

services:
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=my-secret-password
      - POSTGRES_USER=smart
      - POSTGRES_DB=smart
      - POSTGRES_HOST=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "${EXTERNAL_POSTGRES_PORT:-5432}:5432"
    volumes:
      - smart_pgdata_15_2:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    ports:
      - "${EXTERNAL_REDIS_PORT:-6379}:6379"

  backend:
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    container_name: backend
    volumes:
      - ../backend/django:/code
      - ../backend/docker:/code/docker
      - ../frontend:/code/frontend
      - smart_data:/data/
    command: ./runserver.sh

  smart_frontend:
    container_name: smart_frontend
    volumes:
      - ../frontend/:/code
      - /code/node_modules

  celery_worker:
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ../backend/django:/code
      - smart_data:/data/
    command: ./runcelery.sh